<!-- All JavaScript Files-->
<script src="<?= base_url('assets/'); ?>js/default/order.js"></script>
<script src="<?= base_url('assets/'); ?>js/popper.min.js"></script>
<script src="<?= base_url('assets/'); ?>js/waypoints.min.js"></script>
<script src="<?= base_url('assets/'); ?>js/jquery.easing.min.js"></script>
<script src="<?= base_url('assets/'); ?>js/owl.carousel.min.js"></script>
<script src="<?= base_url('assets/'); ?>js/jquery.animatedheadline.min.js"></script>
<script src="<?= base_url('assets/'); ?>js/jquery.counterup.min.js"></script>
<script src="<?= base_url('assets/'); ?>js/wow.min.js"></script>
<script src="<?= base_url('assets/'); ?>js/jarallax.min.js"></script>
<script src="<?= base_url('assets/'); ?>js/jarallax-video.min.js"></script>
<script src="<?= base_url('assets/'); ?>js/default/jquery.passwordstrength.js"></script>
<script src="<?= base_url('assets/'); ?>js/default/dark-mode-switch.js"></script>
<script src="<?= base_url('assets/'); ?>js/default/active.js"></script>
<script src="<?= base_url('assets/'); ?>js/default/check-internet.js"></script>